substitutions:
  name: origami-light-left

packages:
  esp8285: !include common/esp8285.yaml

output:
  - platform: esp8266_pwm
    id: output_brightness
    pin: GPIO4
    
light:
  - platform: monochromatic
    output: output_brightness
    name: "Origami Light Left"
    restore_mode: RESTORE_DEFAULT_OFF

