esphome:
  name: projector
  platform: ESP8266
  board: esp01_1m
  
  includes:
    - "custom/epson_projector.h"

wifi:
  ssid: "frischfunk-iot"
  password: !secret wifi_psk

logger:
  baud_rate: 0

api:
  password: !secret device

ota:
  password: !secret device

web_server:
  port: 80

uart:
  id: bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

switch:
  - platform: custom
    lambda: |-
      auto comp = new EpsonProjectorComponent(id(bus));
      App.register_component(comp);
      return { comp };
    
    switches:
      name: "Projector"
