substitutions:
  name: projector

packages:
  esp8285: !include common/esp8285.yaml

logger:
  baud_rate: 0

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

switch:
  - platform: epson_projector
    name: "Projector"

