substitutions:
  name: projector

packages:
  esp8285: !include common/esp8285.yaml

esphome:
  includes:
    - "custom/epson_projector.h"

uart:
  id: bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

switch:
  - platform: custom
    lambda: |-
      auto comp = new EpsonProjectorComponent(id(bus));
      App.register_component(comp);
      return { comp };
    
    switches:
      name: "Projector"
