substitutions:
  name: prusa-power

packages:
  esp8285: !include common/esp8285.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Prusa Power Button"
    on_press:
      - switch.toggle: switch_power

output:
  - id: output_relay
    platform: gpio
    pin: GPIO12

switch:
  - platform: output 
    id: switch_power
    name: "Prusa Power"
    output: output_relay
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    update_interval: 2s
    current:
      name: Prusa Current
    voltage:
      name: Prusa Voltage
    power:
      name: Prusa Power

status_led:
  pin:
    number: GPIO15
    inverted: True

