substitutions:
  name: prusa-light

packages:
  esp8285: !include common/esp8285.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - light.toggle: main

output:
  - id: light_output
    platform: gpio
    pin: GPIO12

light:
  - platform: binary
    output: light_output
    name: "Prusa Light"
    id: main
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: GPIO13
    inverted: yes

