substitutions:
  name: prusa-light

packages:
  base: !include common/base.yaml
  wifi: !include common/wifi.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - light.toggle: light_main

output:
  - id: output_light
    platform: gpio
    pin: GPIO12

light:
  - platform: binary
    output: output_light
    name: "Prusa Light"
    id: light_main
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: GPIO13
    inverted: True

