esphome:
  name: ${name}
  build_path: ./build/${name}

logger:

api:
  password: !secret device
  reboot_timeout: 1h

external_components:
  - source:
      type: local
      path: components

sensor:
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "ESPHome Version"

binary_sensor:
  - platform: status
    name: "Status"

