wifi:
  ssid: "frischfunk-iot"
  password: !secret wifi_psk

ota:
  password: !secret device

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"

